// 全局异常处理 自定义的中间件
const {catchError} = require("./exception");

module.exports = {
  catchError
}